export const PEOPLE_REQUEST = "PEOPLE_REQUEST";
export const PEOPLE_SUCCESS = "PEOPLE_SUCCESS";
export const PEOPLE_FAILURE = "PEOPLE_FAILURE";

export const VEHICLES_REQUEST = "VEHICLE_REQUEST";
export const VEHICLES_SUCCESS = "VEHICLE_SUCCESS";
export const VEHICLES_FAILURE = "VEHICLE_FAILURE";

export const STARSHIPS_REQUEST = "STARSHIP_REQUEST";
export const STARSHIPS_SUCCESS = "STARSHIP_SUCCESS";
export const STARSHIPS_FAILURE = "STARSHIP_FAILURE";